services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  auth-service:
    build: ./services/auth-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      APP_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
      JWT_PRIVATE_KEY_PATH: /app/config/jwt-private.pem
    volumes:
      - ./services/auth-service/secrets/jwt-private.pem:/app/config/jwt-private.pem:ro

  user-service:
    build: ./services/user-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      APP_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
      JWT_PUBLIC_KEY_PATH: file:/app/config/jwt-public.pem
    volumes:
      - ./services/user-service/keys/jwt-public.pem:/app/config/jwt-public.pem:ro

volumes:
  pg_data: